services:
  postgres:
    image: postgres:15
    container_name: postgres_server_gym
    environment:
      POSTGRES_PASSWORD: rootpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_client_gym
    environment:
      PGADMIN_DEFAULT_EMAIL: randemail@gmail.com
      PGADMIN_DEFAULT_PASSWORD: randpass1
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data: